### ISSUE TITLE
StrictFilePathMarshaler Error 

### ISSUE THREAD

**Issue by K5i4** [deadlydog/VS.DiffAllFiles#5] opened 2017-01-16 14:24 UTC
Receiving the following error diffing any changes:
![image](https://cloud.githubusercontent.com/assets/10601691/21986170/4c8157de-dbf6-11e6-94ac-8380f83689ee.png)

Running VS2015 on Win10. Any ideas?

**Comment by deadlydog** [comment] 2017-03-31 02:53
I noticed this problem as well sometimes in VS 2015. When debugging it, it seemed to be an exception thrown from the LibGit2Sharp library, when asking it for the file path of the .git directory. I wasn't able to get it fixed, but noticed that it happened consistently on some git repositories, but not at all on others. So I'm not certain if something about the file path itself causes this problem (length too long, contains spaces, etc.). You could perhaps try cloning the git repo into a different directory path and see if that fixes the problem.

**Comment by deadlydog** [comment] 2017-06-12 15:26
So yeah, it looks like this is an issue with GitTasks, which LibGit2Sharp uses (https://github.com/GitTools/GitVersion/issues/720). The workaround I have found in the past is to delete and reclone the repository.

For the VS 2017 version of Diff All Files, I'm using a newer version of LibGit2Sharp that hopefully doesn't have this problem; I'm going to wait a bit and see if anybody reports it. If not, then I'll try and update the VS 2015 version of the extension as well. The only reason I'm a bit hesitant to do this is because I no longer have VS 2015 installed, so I can't test the new version of the extension before publishing it. If I make a new VS 2015 version, I may post the .vsix file here to try and have somebody confirm it works properly before publishing it to the VS Marketplace.

**Comment by K5i4** [comment] 2017-06-13 16:30
I still have VS2015 installed so I'm willing to test it if you do.

**Comment by deadlydog** [comment] 2017-06-14 07:34
Hey @K5i4 here's the new version of Diff All Files for VS 2015 (v1.2.1). Can you give it a shot and let me know:
1. If it still loads correctly and works as expected.
2. If it fixes the `StrictFilePathMarshaler` error you reported (if you are still able to reproduce it consistently on the currently published version of the tool that is).

If you do get an error, can you please provide the full error text here, and screenshot if possible.

[VS.DiffAllFiles.VS2015.vsix.zip](https://github.com/deadlydog/VS.DiffAllFiles/files/1073825/VS.DiffAllFiles.VS2015.vsix.zip)

I had to add ".zip" to the filename in order to upload it to GitHub, so once you've downloaded it just remove that part so it has a regular ".vsix" extension, and then you should be able to install it.

I look forward to hearing the results. Thanks!

**Comment by deadlydog** [comment] 2017-06-20 03:16
I had a coworker test this v1.2.1 out and it seemed to work properly, so I've published it to the VS Marketplace. Hopefully this issue is fixed now. I'm going to close this issue, but it can be reopened if we discover that the problem still exists.

**Closed by deadlydog** 2017-06-20 03:16 UTC
Labels: bug

**Comment by K5i4** [comment] 2017-06-20 08:32
Sorry, I did try this (but got distracted when my employer announced a whole load of redundancies!). I couldn't reproduce the original issue on 2015 so I can't say whether it fixes the original issue but I've seen no issue with the new version either.
