### ISSUE TITLE
Installation fails on VS2019 v16.1.1

### ISSUE THREAD

**Issue by Invvard** [deadlydog/VS.DiffAllFiles#33] opened 2019-05-24 18:34 UTC
It is impossible to install [your extension](https://marketplace.visualstudio.com/items?itemName=deadlydog.DiffAllFilesforVS2019) on VS2019 v16.1.1

Here is a screenshot of the error :
![error](https://user-images.githubusercontent.com/7305493/58348829-b2cf3f00-7e2f-11e9-882f-62d115ffef7c.png)

And the logs :
[dd_VSIXInstaller_20190524142932.log](https://github.com/deadlydog/VS.DiffAllFiles/files/3218179/dd_VSIXInstaller_20190524142932.log)

_Originally posted by @Invvard in https://github.com/deadlydog/VS.DiffAllFiles/issues/32#issuecomment-495743306_

**Comment by deadlydog** [comment] 2019-05-24 18:58
When I updated my VS 2019 to v16.1 the extension was still installed, but after uninstalling it I'm also not able to install the extension on v16.1+. I believe the problem is I have the `Version Range` defined at `[16.0]`. I'll adjust that and get a new version posted soon. Thanks for reporting it!

**Comment by deadlydog** [comment] 2019-05-24 19:12
I just posted [v1.0.3 of the extension](https://marketplace.visualstudio.com/items?itemName=deadlydog.DiffAllFilesforVS2019). Can you give that a shot and let me know if it fixes the issue for you please @Invvard. It did the trick for me. Thanks.

**Comment by deadlydog** [comment] 2019-05-24 19:14
Hmmm, while that fixed the installation issue, I'm now getting the same error as reported in #32. I think it's safe to close this issue though.

**Closed by deadlydog** 2019-05-24 19:14 UTC
Labels: bug
